global_args:
  trainer_backend: pl
  enable_deepspeed: false
  enable_ptv2: false
  enable_lora: true
  load_in_bit: 0
  config_merge: {}
  # 模型权重 ， 对应 config.constant_map.py
  model_name: Qwen-7B-Chat

  # one of auto 16 bf16 32
  precision: auto
  quantization_config:
    load_in_8bit: false
    load_in_4bit: false
    llm_int8_threshold: 6.0
    llm_int8_has_fp16_weight: false
    bnb_4bit_compute_dtype: float16  # one of float16  bfloat16 float32
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4




global_models_mapper: 

    Qwen-1_8B-Chat: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-1_8B-Chat
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-1_8B-Chat
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-1_8B-Chat
    

    Qwen-1_8B: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-1_8B
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-1_8B
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-1_8B
    


    Qwen-7B-Chat: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-7B-Chat
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-7B-Chat
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-7B-Chat
    

    Qwen-7B: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-7B
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-7B
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-7B
    

    Qwen-14B-Chat: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-14B-Chat
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-14B-Chat
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-14B-Chat
    

    Qwen-14B: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-14B
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-14
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-14B
    

    Qwen-72B-Chat: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-72B-Chat
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-72B-Chat
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-72B-Chat
    

    Qwen-72B: 
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-72B
        config_name: /data/nlp/pre_models/torch/qwen/Qwen-72B
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen-72B
    


